apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.service.port }}
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.hostname }}