apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: {{ .Chart.Name }}