{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vmchooserfrontend.serviceAccountName" . }}
  labels:
{{ include "vmchooserfrontend.labels" . | nindent 4 }}
{{- end -}}
