apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
  - {{ .Values.hostname }}
  gateways:
  - {{ .Chart.Name }}-gateway
  http:
  - match:
    - uri:
        prefix: /static/
        exact: /index.html
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
      allowOrigin:
      - "*"
      allowMethods:
      - POST
      - GET
      - DELETE
      - PATCH
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - "*"